sudo: true
dist: xenial
language: python

python:
  - 3.6
  - 3.7

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - sudo apt-get install postgresql-9.6-postgis-2.3 postgis -y -q
  - psql -c 'create database envirobase;' -U postgres
  - psql -U postgres -c "create extension postgis" -d envirobase
  - export FLASK_APP="$TRAVIS_BUILD_DIR/envirobase"
  - export FLASK_DEBUG=1

install: make setup

script: make test
