DROP TABLE IF EXISTS site CASCADE;

DROP TABLE IF EXISTS unit CASCADE;
 
DROP TABLE IF EXISTS location CASCADE;

DROP TABLE IF EXISTS parameters CASCADE;

DROP TABLE IF EXISTS sample_results CASCADE;
